### ISSUE TITLE
Question about `current_stack_pointer`

### ISSUE THREAD

**Issue by mrnugget** [playXE/migc#1]
Hey there! First of all: thanks for putting `migc` on GitHub! I've been looking into writing a conservative GC and it's super helpful to look at `migc` and see how you do stack scanning.

I wanted to send you an email but then figured: why not open an issue? So, this is a *question* and not a bug.

How is `current_stack_pointer` supposed to work?

https://github.com/playXE/migc/blob/fb3b807a2698a1066b3fffd6d2effce5b9c64ab7/migc.h#L303-L309

There's two things I don't understand:

1. If I understand it correctly it tries to take the address of an undeclared local variable (`sp`). Shouldn't this be something like
    ```c
    int dummy
    return &dummy
    ```
2. When I try to compile the `example.c` with
    ```
    $ gcc -O3  migc.c migc.h example.c -o example -L -Wl,-rpath= -L/home/mrnugget/code/clones/migc/mimalloc/out/release -Wl,-rpath=/home/mrnugget/code/clones/migc/mimalloc/out/release -pthread -lmimalloc
    ```
    I get a bunch of warnings but also this error:
    ```c
    /usr/bin/ld: /tmp/ccjNSGu8.o: in function `current_stack_pointer':
    example.c:(.text+0x80): multiple definition of `current_stack_pointer'; /tmp/ccoWCpKL.o:migc.c:(.text+0x240): first defined here
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:15: example] Error 1
    ```

It seems to me like `current_stack_pointer` *should* be inlined, right?

**Comment by playXE** [comment]
Hi! It should not be in fact inlined, if it gets inlined compiler can reorder or opt-out stack pointer access. 

About the error. It seems that you somehow included the file twice? I fixed one include problem with stdio atm though

**Comment by mrnugget** [comment]
Hey! Thanks for the reply :)

> It should not be in fact inlined, if it gets inlined compiler can reorder or opt-out stack pointer access.

But if it's not inlined it will have it's on segment on stack then that gets then popped off after it's called, right?

Also: where is `sp` defined?

> About the error. It seems that you somehow included the file twice? I fixed one include problem with stdio atm though

I didn't do anything, I'm just trying to compile the `example.c` file in this repository.

**Comment by playXE** [comment]
> I didn't do anything, I'm just trying to compile the example.c file in this repository.

Ah I see now, you should compile everything separately and then link example with libmigc.so. 

> But if it's not inlined it will have it's on segment on stack then that gets then popped off after it's called, right?

It does not matter as it will point to read-able stack space that GC can scan for pointers, it does not really matter if this pointer is from popped segment. JavaScriptCore in fact uses similar function

> Also: where is sp defined?

It's in the same function, it takes address of itself

**Comment by mrnugget** [comment]
> Ah I see now, you should compile everything separately and then link example with libmigc.so.

Alright, got it!

> It's in the same function, it takes address of itself

OHHH! Now I get it! The declaration of the pointer is done first and then assigned the value of its own address. Got it! Thank you!
